### ISSUE TITLE
Ghost Gulp Rollup Preset: CSS path in system.json and gulp dest are different.

### ISSUE THREAD

**Issue by aMediocreDad** [ghost91-/foundry-factory#12]
Summary: system.json = ["styles/name-of-system.css"], gulpfile = ["css/name-of-system.css"] 

Title, as defined in gulpfile:
https://github.com/ghost91-/foundry-factory/blob/4efee15dc11c94ba348acf3148d4aaafd4324572/template/ghost-gulp-rollup/gulpfile.js.njk#L45

Title, as defined in system.json:
https://github.com/ghost91-/foundry-factory/blob/4efee15dc11c94ba348acf3148d4aaafd4324572/src/presets/ghost-gulp-rollup/generate-programmatic-files.ts#L161

EDIT: Should also be noted that on Windows `path.join` doesn't play nice when used as a `src()`. It will in this case pipe the whole `src/styles` into `dist/css/`.

**Comment by ghost91-** [comment]
Thanks for the report. I just pushed a commit to fix the mismatch between the directory names (https://github.com/ghost91-/foundry-factory/commit/787e353597cdb7ca53ed49114c1bcbc05f05a752)

Unfortunately, I don't really have a good idea what to do about this windows issue (not even sure if I understood your report completely). I'll try to reproduce it on my windows machine when I find the time.

However, if you have any suggestions about how to improve / fix this, I'm happy to add them.

**Comment by ghost91-** [comment]
Ah, just did a small google search and apparently, gulp recommends to just use unix paths for `src` etc. and things will magically work (see e.g. https://github.com/gulpjs/gulp/issues/1847). I will adjust it accordingly.

**Comment by ghost91-** [comment]
I think I have a solution now, I'll test it on windows later on.

**Comment by aMediocreDad** [comment]
Looks good! That should do it:)

And sorry, wrote it late at night so it wasn't my most coherent report.

**Comment by ghost91-** [comment]
Tested it and it seems to work fine. Going to create a patch release now
