### ISSUE TITLE
[Gulp + Rollup Preset] gulp-sass broken on node 16+

### ISSUE THREAD

**Issue by OfficerHalf** [ghost91-/foundry-factory#18]
Less a problem with your code and more just that gulp-sass hasn't removed/updated its dependency on node-sass (see the [large amount of issues](https://github.com/dlmanning/gulp-sass/issues) about it on the gulp-sass repo). But for now, trying to create a new module with sass fails on the install step with a massive wall of build errors. Might be worth figuring out an alternative to gulp-sass or warning if on node 16+.

**Comment by ghost91-** [comment]
Hey @OfficerHalf, thanks for the report! It seems that witching to [gulp-dart-sass](https://www.npmjs.com/package/gulp-dart-sass) fixes the problem. Could you verify that it works for you on the branch 018-switch-to-gulp-dart-sass?

**Comment by OfficerHalf** [comment]
Yeah, no error at the install step using that branch. 👍
