### ISSUE TITLE
[Gulp + Rollup Preset] husky setup fails on windows

### ISSUE THREAD

**Issue by OfficerHalf** [ghost91-/foundry-factory#19]
Ironically, it seems like the [fix](https://github.com/ghost91-/foundry-factory/pull/7/files#diff-a668b8c71daaa111e957ef5f34c86e690922128b0343920d299324b42654b13b) in #7 broke initializing husky on windows in a different way.

The following is the output:
```
Foundry Factory 0.6.0
? Please select whether to create a module or a system: Module
✔ Created working directory
✔ Initialized new git repository
? Please pick a preset (links point to the documentation of the preset): ghost's Gulp + Rollup Preset
? Check the features needed for your project: TypeScript, Linter & Formatter (ESLint & Prettier)
✔ Created programmatic files
✔ Created files from templates
✔ Created additional directories
✔ Installed dependencies
✖ Failed to execute post installation commands
Failed to create project at C:\devel\fvtt-fantasy-name-generators-2
Error: Command failed: npx husky add .husky/pre-commit \"npx lint-staged\"
```

In both standard cmd and also powershell the following command generates the pre-commit file correctly:  
`npx husky add .husky/pre-commit "npx lint-staged"`
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
```

The escaped quotes do nothing on cmd (husky doesn't understand the arguments), but generates this monstrosity in powershell:
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

\\npx lint-staged"
```

**Comment by ghost91-** [comment]
Hi @OfficerHalf, thanks for the report. I will try to have a look at this but Windows support is always a bit difficult because it's not my main operating system. If you have any insights about how to address this issue, any help is greatly appreciated.

**Comment by OfficerHalf** [comment]
I think just using bog standard double quotes should solve it. I can make a PR. 🙂

**Comment by ghost91-** [comment]
I think I tried that. But if you can make a PR and verify it works for you on windows, that’s fine for me
